// src/services/mockData/initialAnalysis.ts
import { Reflection, Summary, Task, ThemeItem, Trend } from '../../types';

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    title: '给客户发送会议纪要与验收方案',
    description: '整理会议要点并发送给客户确认技术架构与里程碑时间表',
    category: '沟通',
    priority: '高',
    startTime: new Date(Date.now() - 3600000).toISOString(),
    dueTime: new Date(Date.now() + 4 * 3600000).toISOString(),
    reminderTime: new Date(Date.now() + 2 * 3600000).toISOString(),
    repeatRule: '无',
    estimatedMinutes: 30,
    status: '未开始',
    steps: [
      { content: '核对纪要关键共识', done: true },
      { content: '附带交付物清单与时间线', done: false },
      { content: '邮件发出并抄送项目组', done: false },
    ],
    sourceReflectionId: 'ref-1',
    checkInTypeId: null,
    feedback: {},
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'task-2',
    title: '准备项目架构讲解材料',
    description: '制作 PPT 并准备演讲要点，涵盖前端组件化与数据流动闭环',
    category: '项目',
    priority: '高',
    startTime: new Date().toISOString(),
    dueTime: new Date(Date.now() + 86400000).toISOString(),
    reminderTime: null,
    repeatRule: '无',
    estimatedMinutes: 120,
    status: '进行中',
    steps: [
      { content: '收集核心业务流程图', done: true },
      { content: '整理关键指标与成效对比', done: false },
    ],
    sourceReflectionId: 'ref-2',
    checkInTypeId: null,
    feedback: {},
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-3',
    title: '完成技术专栏阅读与摘抄',
    description: '通读状态机设计模式与离线持久化最佳实践',
    category: '学习',
    priority: '中',
    startTime: null,
    dueTime: new Date(Date.now() + 86400000).toISOString(),
    repeatRule: '无',
    estimatedMinutes: 60,
    status: '已完成',
    steps: [
      { content: '阅读核心章节', done: true },
      { content: '记录要点并归纳代码片段', done: true },
    ],
    sourceReflectionId: 'ref-2',
    checkInTypeId: 'type-1',
    feedback: {
      completedTime: new Date(Date.now() - 7200000).toISOString(),
      executionDurationMinutes: 55,
      behaviorImprovement: ['提前规划时间', '减少手机干扰'],
    },
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'task-4',
    title: '预约下周体检与牙齿检查',
    description: '在医院小程序预约周五上午的常规健康体检',
    category: '健康',
    priority: '低',
    startTime: null,
    dueTime: new Date(Date.now() + 3 * 86400000).toISOString(),
    repeatRule: '无',
    estimatedMinutes: 15,
    status: '延期',
    steps: [],
    sourceReflectionId: null,
    checkInTypeId: null,
    feedback: {
      delayType: '内部',
      reason: '工作安排冲突，需要重新协调时间',
    },
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'task-5',
    title: '每日早起与晨读打卡',
    description: '早上 7:00 前起床，晨读 15 分钟',
    category: '习惯',
    priority: '低',
    startTime: new Date().toISOString(),
    dueTime: null,
    repeatRule: '每天',
    estimatedMinutes: 20,
    status: '进行中',
    steps: [],
    sourceReflectionId: null,
    checkInTypeId: 'type-4',
    feedback: {},
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'task-6',
    title: '制定下月工作与学习规划',
    description: '列出下月各领域的重点目标与行动方案',
    category: '规划',
    priority: '中',
    startTime: null,
    dueTime: new Date(Date.now() + 10 * 86400000).toISOString(),
    repeatRule: '每月',
    estimatedMinutes: 90,
    status: '未开始',
    steps: [],
    sourceReflectionId: null,
    checkInTypeId: null,
    feedback: {},
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
];

export const initialReflections: Reflection[] = [
  {
    id: 'ref-1',
    eventDescription: '与客户深入沟通项目需求，双方对初步框架达成共识，但在验收细则上仍需进一步书面化。',
    emotion: '平静',
    actionTaken: '在白板上梳理逻辑架构，当场记录要点并在会后输出纪要。',
    result: '客户认可方案方向，约定周三前提供完整验收指标。',
    aiSummary: {
      eventSummary: '与客户讨论需求并达成初步方案',
      goodPoints: '沟通顺畅且当场记录要点',
      ignoredFactors: '未提前准备细化指标模版',
      improvementPoints: '需在方案中明确量化验收标准',
      nextSuggestion: '准备详细技术方案与验收标准草稿',
      suggestedTask: '制定详细技术方案与验收细则',
      citations: {
        memoryIds: ['mem-1'],
        photoIds: ['photo-1'],
      },
    },
    relatedMemoryIds: ['mem-1'],
    relatedPhotoIds: ['photo-1'],
    relatedTaskIds: ['task-1'],
    relatedSummaryIds: [],
    isUserConfirmed: true,
    createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: 'ref-2',
    eventDescription: '复习复杂状态管理与 Provider/Context 架构实践，梳理了数据流转图。',
    emotion: '满足',
    actionTaken: '整理笔记并画出组件与状态存储的拓扑流转图。',
    result: '理清了响应式更新与幂等事件派发的边界。',
    aiSummary: {
      eventSummary: '深入复习状态管理并整理架构图',
      goodPoints: '主动归纳设计模式与实现细节',
      ignoredFactors: '实践时间稍微偏短',
      improvementPoints: '需要在真实交互业务中进一步验证边界',
      nextSuggestion: '建立核心组件单元测试样例',
      suggestedTask: '编写状态机状态流转单元测试',
      citations: {
        memoryIds: ['mem-2'],
        photoIds: ['photo-2'],
      },
    },
    relatedMemoryIds: ['mem-2'],
    relatedPhotoIds: ['photo-2'],
    relatedTaskIds: ['task-2'],
    relatedSummaryIds: [],
    isUserConfirmed: true,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

export const initialTrends: Trend[] = [
  {
    id: 'trend-1',
    trendName: '给客户发送会议纪要与验收方案',
    category: '沟通',
    score: -2,
    direction: '改善',
    weight: 6,
    evidence: [
      {
        eventId: 'ev-1',
        taskId: 'task-1',
        event: 'completed',
        delta: -1,
        time: new Date(Date.now() - 86400000).toISOString(),
        category: '沟通',
        behaviorImprovement: ['提前草拟模版'],
      },
      {
        eventId: 'ev-2',
        taskId: 'task-8',
        event: 'completed',
        delta: -1,
        time: new Date(Date.now() - 2 * 86400000).toISOString(),
        category: '沟通',
      },
    ],
    cluster: '沟通',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trend-2',
    trendName: '完成技术专栏阅读与摘抄',
    category: '学习',
    score: -3,
    direction: '改善',
    weight: 9,
    evidence: [
      {
        eventId: 'ev-3',
        taskId: 'task-3',
        event: 'completed',
        delta: -1,
        time: new Date(Date.now() - 7200000).toISOString(),
        category: '学习',
        behaviorImprovement: ['提前规划时间', '减少手机干扰'],
      },
    ],
    cluster: '学习',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trend-3',
    trendName: '体检预约',
    category: '健康',
    score: 1.0,
    direction: '恶化',
    weight: 2,
    evidence: [
      {
        eventId: 'ev-4',
        taskId: 'task-4',
        event: 'delayed',
        delta: 1.0,
        time: new Date(Date.now() - 3 * 86400000).toISOString(),
        category: '健康',
      },
    ],
    cluster: '健康',
    updatedAt: new Date().toISOString(),
  },
];

export const initialThemes: ThemeItem[] = [
  {
    id: 'theme-1',
    themeName: '学习',
    weight: 9,
    direction: '改善',
    evidence: initialTrends[1].evidence,
    clusterNames: ['学习'],
    trendNames: ['完成技术专栏阅读与摘抄'],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'theme-2',
    themeName: '沟通',
    weight: 6,
    direction: '改善',
    evidence: initialTrends[0].evidence,
    clusterNames: ['沟通'],
    trendNames: ['给客户发送会议纪要与验收方案'],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'theme-3',
    themeName: '健康',
    weight: 2,
    direction: '恶化',
    evidence: initialTrends[2].evidence,
    clusterNames: ['健康'],
    trendNames: ['体检预约'],
    updatedAt: new Date().toISOString(),
  },
];

export const initialSummaries: Summary[] = [
  {
    id: 'sum-1',
    type: '周',
    periodStart: new Date(Date.now() - 7 * 86400000).toISOString(),
    periodEnd: new Date().toISOString(),
    content: '本周整体行为模式呈现稳步向好势头。学习与技术研读保持每日投入，完成率达 85%；工作沟通环节通过提前记录白板与纪要提高了共识达成速度；唯独健康作息因偶有加班稍有滞后，建议下周固定晚间收尾时间。',
    themes: [
      { name: '学习', direction: '改善', weight: 9 },
      { name: '沟通', direction: '改善', weight: 6 },
      { name: '健康', direction: '恶化', weight: 2 },
    ],
    highlights: [
      '连续 5 天完成习惯打卡与技术阅读笔记',
      '客户沟通形成标准化白板与纪要模板',
      'AI 反思系统记录并沉淀了关键设计认知',
    ],
    taskSuggestions: [
      '制定下周固定晨读与作息时间表',
      '建立项目验收细则核对清单',
      '安排体检改期并在日历中锁定时间',
    ],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'sum-2',
    type: '月',
    periodStart: new Date(Date.now() - 30 * 86400000).toISOString(),
    periodEnd: new Date().toISOString(),
    content: '过去一个月系统性建立了生活与工作闭环。任务完成率由上旬的 62% 爬升至下旬的 88%。通过及时记录事实反思，规避了大量重复沟通返工，个人掌控感与专注力显著提高。',
    themes: [
      { name: '学习', direction: '改善', weight: 22 },
      { name: '项目', direction: '改善', weight: 18 },
      { name: '规划', direction: '稳定', weight: 10 },
    ],
    highlights: [
      '月度任务累计达成 28 项，行为改进沉淀 14 条',
      '习惯打卡总天数达 24 天，达成度超 80%',
      '成功输出 3 篇系统性技术反思与架构总结',
    ],
    taskSuggestions: [
      '开启下一阶段季度战略里程碑分解',
      '保持早起与晨跑运动周均 3 次以上',
    ],
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'sum-3',
    type: '年',
    periodStart: new Date(new Date().getFullYear(), 0, 1).toISOString(),
    periodEnd: new Date().toISOString(),
    content: '年度成长飞轮已经形成。从被动应对任务转向以“记录-反思-执行-沉淀”为轴心的自驱生活节奏。自我效能与情绪稳定度均有肉眼可见的蜕变。',
    themes: [
      { name: '学习', direction: '改善', weight: 85 },
      { name: '项目', direction: '改善', weight: 70 },
      { name: '习惯', direction: '改善', weight: 55 },
      { name: '健康', direction: '稳定', weight: 30 },
    ],
    highlights: [
      '全年积累高价值生活反思与工作复盘 80+ 篇',
      '专业技术领域完成全景图梳理与项目落地',
      '打卡习惯从零建立并巩固为日常自然反射',
    ],
    taskSuggestions: [
      '设立新一年年度核心目标三大战役',
      '深化系统自动化与跨平台数据同步',
    ],
    annualData: {
      annualTheme: '从自律走向自驱的觉醒之年',
      highlights: [
        '学习成长曲线连续 4 个季度呈现上扬动能',
        '沉淀 80+ 份高质量事实反思与行为证据链',
        '任务执行延期率相比上半年降低 42%',
      ],
      behaviorTrend: '显著改善：主动规划率提升，逃避型延期归零，深度专注时长日均增加 45 分钟。',
      moodTrend: '情绪稳定性大幅提高，焦虑频次减少，平静与满足感成为主流心境。',
      lifeRhythm: '建立了稳定的早起打卡、晨间散步、日间执行、睡前复盘的节奏闭环。',
      annualReflection: '真正决定个人成长速度的不是宏大的口号，而是每一件小事被记录、被审视、被迭代时的诚实与坚持。',
      nextYearSuggestions: [
        '制定下一年度专业技术深耕路线图',
        '建立每周固定复盘与生活休整日',
        '启动系统化健康与耐力训练计划',
        '记录更多家庭与生活中有温度的闪光瞬间',
      ],
    },
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];
